Repository neomatrix369/nlp_profiler, pull requests merged in 2020-10, with the labels that each got.

#11 Adding Table of Contents to the README
  README.md
Labels: Hacktoberfest, documentation, enhancement

#17 Fix sentence count issue
  nlp_profiler/sentences.py
  tests/acceptance_tests/data/expected_profiled_dataframe.csv
  tests/acceptance_tests/data/expected_profiled_dataframe_no_granular.csv
  tests/acceptance_tests/data/expected_profiled_dataframe_no_high_level.csv
  tests/granular/test_sentences.py
  tests/high_level/test_spelling_check.py
Labels: bug, hacktoberfest, hacktoberfest-accepted

#19 Creating ci/cd github action
  .github/workflows/new-or-updated-changes.yml
  README.md
  developer-guide.md
  requirements-dev.txt
  requirements-linux-dev.txt
Labels: ci/cd, enhancement, github-action

#25 Adding the much helpful github templates
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question_or_discussion.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CHANGELOG.md
  CONTRIBUTING.md
  CREDITS_AND_SUPPORTERS.md
Labels: documentation, enhancement, templates

#26 Rename Github action workflow
  .github/workflows/end-to-end-flow.yml
  README.md
Labels: github-action, misnaming

#27 Renaming column words_count to count_words
  nlp_profiler/constants.py
  nlp_profiler/granular_features.py
  nlp_profiler/words.py
  notebooks/google-colab/nlp_profiler-granular.ipynb
  notebooks/google-colab/nlp_profiler.ipynb
  notebooks/jupyter/nlp_profiler-large-dataset.ipynb
  notebooks/jupyter/nlp_profiler.ipynb
  tests/acceptance_tests/data/expected_profiled_dataframe.csv
  tests/acceptance_tests/data/expected_profiled_dataframe_no_high_level.csv
Labels: hacktoberfest, misnaming, typos or spelling mistakes

#29 Refactor: split the original generate_features.py module
  nlp_profiler/generate_features/__init__.py
  nlp_profiler/generate_features/parallelisation_methods/__init__.py
Labels: code-quality, refactor

#37 Refactor high level features
  nlp_profiler/core.py
  nlp_profiler/high_level_features/__init__.py
  nlp_profiler/high_level_features/grammar_quality_check.py
  nlp_profiler/high_level_features/sentiment_polarity.py
  nlp_profiler/high_level_features/sentiment_subjectivity.py
  nlp_profiler/high_level_features/spelling_quality_check.py
  notebooks/google-colab/nlp_profiler-granular.ipynb
  notebooks/jupyter/nlp_profiler-granular.ipynb
  slow-tests/performance_tests/test_perf_grammar_check.py
  slow-tests/performance_tests/test_perf_spelling_check.py
  tests/high_level/test_grammar_check.py
  tests/high_level/test_sentiment_polarity.py
  tests/high_level/test_sentiment_subjectivity.py
  tests/high_level/test_spelling_check.py
Labels: code-quality, refactor

#38 Fixing the Pull request template (Github templates)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: templates

#39 Amend caching configuration of GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/end-to-end-flow.yml
Labels: ci/cd, github-action, performance

#40 run nbqa-black
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  notebooks/google-colab/nlp_profiler-granular.ipynb
  notebooks/google-colab/nlp_profiler.ipynb
  notebooks/jupyter/nlp_profiler-granular.ipynb
  notebooks/jupyter/nlp_profiler-large-dataset.ipynb
  notebooks/jupyter/nlp_profiler.ipynb
  pyproject.toml
Labels: code-quality

#41 Scope the nbqa analysis to the notebooks folder
  .pre-commit-config.yaml
Labels: code-quality, notebook/kernel/colab

#42 Put immutable ref in pre-commit-config
  .pre-commit-config.yaml
Labels: code-quality, github-action

#43 Github templates: updating the text in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement, templates

#44 Add docs for developers
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  developer-guide.md
  notebooks/README.md
Labels: documentation, notebook/kernel/colab

#45 Merging notebooks into a single version
  .gitignore
  notebooks/README.md
  notebooks/google-colab/nlp_profiler-granular.ipynb
  notebooks/jupyter/nlp_profiler.ipynb
  notebooks/nlp_profiler-granular.ipynb
  notebooks/nlp_profiler-large-dataset.ipynb
  notebooks/nlp_profiler.ipynb
Labels: documentation, notebook/kernel/colab, refactor

#48 Fix GitHub action to build on Windows instances
  .github/workflows/end-to-end-flow.yml
  CHANGELOG.md
Labels: limitations

#50 Add gitter.im badge and link to the README page
  .gitignore
  README.md
Labels: communication, community, documentation, enhancement
